/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.psi.biblioteca.ui;

import br.com.psi.biblioteca.ui.ViewPermissao;
import br.com.psi.biblioteca.ui.ViewGrupo;
import br.com.psi.biblioteca.ui.ViewUsuario;
import br.com.psi.biblioteca.dao.GrupoDao;
import br.com.psi.biblioteca.dao.PermissaoDao;
import br.com.psi.biblioteca.exception.DaoException;
import br.com.psi.biblioteca.ui.ViewSobre;
import br.com.psi.biblioteca.util.JpaUtil;
import java.awt.Dimension;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Criteria;
import org.hibernate.Session;

/**
 *
 * @author lucas
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        menuCadastroPermissao = new javax.swing.JMenuItem();
        menuCadastroUsuario = new javax.swing.JMenuItem();
        menuCadastroGrupo = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuRelatorio = new javax.swing.JMenu();
        menRelGrupos = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        menuCadastro.setText("Cadastro");
        menuCadastro.setEnabled(false);
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });

        menuCadastroPermissao.setText("Permissão");
        menuCadastroPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroPermissaoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroPermissao);

        menuCadastroUsuario.setText("Usuario");
        menuCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroUsuarioActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroUsuario);

        menuCadastroGrupo.setText("Grupo");
        menuCadastroGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroGrupoActionPerformed(evt);
            }
        });
        menuCadastro.add(menuCadastroGrupo);

        jMenuItem2.setText("Movimentações");
        menuCadastro.add(jMenuItem2);

        jMenuBar1.add(menuCadastro);

        menuRelatorio.setText("Relatório");
        menuRelatorio.setEnabled(false);

        menRelGrupos.setText("Permissões");
        menRelGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menRelGruposActionPerformed(evt);
            }
        });
        menuRelatorio.add(menRelGrupos);

        jMenuItem4.setText("Movimentações");
        menuRelatorio.add(jMenuItem4);

        jMenuBar1.add(menuRelatorio);

        jMenu3.setText("Opções");

        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem5.setText("Sobre");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        setSize(new java.awt.Dimension(829, 598));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastroPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroPermissaoActionPerformed
        ViewPermissao telaPermissao = new ViewPermissao();
        centralizaForm(telaPermissao);
        telaPermissao.setVisible(true);
        Desktop.add(telaPermissao);

    }//GEN-LAST:event_menuCadastroPermissaoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que sair?", "Atenção", JOptionPane.YES_NO_OPTION);//cria uma caixa de diálogo, aponta pra NULL, Faz a pergunta, nome do titulo, e a opção padronizada sim ou não
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed


    }//GEN-LAST:event_menuCadastroActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        ViewSobre telaSobre = new ViewSobre();
        centralizaForm(telaSobre);
        telaSobre.setVisible(true);
        Desktop.add(telaSobre);  // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroUsuarioActionPerformed
       
        ViewUsuario telaUsuario = new ViewUsuario();
        centralizaForm(telaUsuario);
        telaUsuario.setVisible(true);
        Desktop.add(telaUsuario);
    }//GEN-LAST:event_menuCadastroUsuarioActionPerformed

    private void menuCadastroGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroGrupoActionPerformed
         
        ViewGrupo telaGrupo = new ViewGrupo();
        centralizaForm(telaGrupo);
        telaGrupo.setVisible(true);
        Desktop.add(telaGrupo);
    }//GEN-LAST:event_menuCadastroGrupoActionPerformed

    private void menRelGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menRelGruposActionPerformed
       PermissaoDao pd = new PermissaoDao();
        int confirma = JOptionPane.showConfirmDialog(null,"Confirma a impressão deste relatório?","Atenção",JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION){
           try {
               //imprimindo relatório com o framework JasperReports
             JRDataSource jrDataSource = new JRBeanCollectionDataSource(pd.all());
             String sourceName = "/home/lucas/NetBeansProjects/oi/Gerenciador-de-permiss-o/src/main/java/br/com/map/biblioteca/report/permissao.jrxml";
             JasperReport report = JasperCompileManager.compileReport(sourceName);
             JasperPrint filledReport = JasperFillManager.fillReport(report,null, jrDataSource);
             JasperViewer.viewReport(filledReport,false);    
                               
           } catch (Exception ex) {
               Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
           }
           
           
        }
    }//GEN-LAST:event_menRelGruposActionPerformed

    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = Desktop.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
         (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    public static javax.swing.JMenuItem menRelGrupos;
    public static javax.swing.JMenu menuCadastro;
    public static javax.swing.JMenuItem menuCadastroGrupo;
    public static javax.swing.JMenuItem menuCadastroPermissao;
    public static javax.swing.JMenuItem menuCadastroUsuario;
    public static javax.swing.JMenu menuRelatorio;
    // End of variables declaration//GEN-END:variables
}
