/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.psi.biblioteca.ui;

import br.com.psi.biblioteca.exception.DaoException;
import br.com.psi.biblioteca.facade.Facade;
import br.com.psi.biblioteca.model.Grupo;
import br.com.psi.biblioteca.model.Permissao;
import br.com.psi.biblioteca.model.Usuario;
import br.com.psi.biblioteca.ui.ViewGrupo;
import br.com.psi.biblioteca.ui.ViewPermissao;
import br.com.psi.biblioteca.ui.ViewPrincipal;
import br.com.psi.biblioteca.util.SimpleFactoryUtil;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class ViewUsuario extends javax.swing.JInternalFrame {

    private Facade facade = new Facade();

    public ViewUsuario() {
        initComponents();
        povoarTabelaUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrupo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bntAdicionar = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        bntExcluir = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtGrupo = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setVisible(true);

        tblGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Permissão"
            }
        ));
        tblGrupo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblGrupoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tblGrupo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Grupos Cadastrados ");

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "CPF", "Nome", "Grupo"
            }
        ));
        tblUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuarioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsuario);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Usuários Cadastrados");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Id");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Cpf");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nome");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cod Grupo");

        bntAdicionar.setText("ADICIONAR");
        bntAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAdicionarActionPerformed(evt);
            }
        });

        bntEditar.setText("EDITAR");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        bntExcluir.setText("EXCLUIR");
        bntExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntExcluirActionPerformed(evt);
            }
        });

        txtId.setEnabled(false);

        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        txtGrupo.setText("                        01");
        txtGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtGrupoMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtGrupoMouseClicked(evt);
            }
        });
        txtGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGrupoActionPerformed(evt);
            }
        });

        txtSenha.setText("ield1");

        jLabel7.setFont(new java.awt.Font("TakaoPGothic", 1, 12)); // NOI18N
        jLabel7.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel2))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(33, 33, 33)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)))
                                                .addComponent(jLabel6))
                                            .addGap(9, 9, 9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(4, 4, 4))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(bntAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bntExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntEditar)
                    .addComponent(bntExcluir)
                    .addComponent(bntAdicionar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrupoActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        if (txtCpf.getText().toString().equals(null) && txtNome.getText().toString().equals(null) && txtGrupo.getText().toString().equals(null) && txtId.getText().toString().equals(null)
                || txtCpf.getText().toString().equals("") && txtNome.getText().toString().equals("") && txtGrupo.getText().toString().equals(null) && txtId.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Erro ao Editar Usuário, Dados inválidos!");
        } else {
            Usuario u = SimpleFactoryUtil.criarUsuario();
            try {
                u = facade.buscarUsuario(Long.parseLong(txtId.getText().toString()));
                u.setCpf(Long.parseLong(txtCpf.getText().toString()));
                u.setNome(txtNome.getText().toString());
                u.setSenha(txtSenha.getText());
                Grupo encontrado = SimpleFactoryUtil.criarGrupo();
                try {
                    encontrado = facade.buscarGrupo(Long.parseLong(txtGrupo.getText()));
                    u.setGrupo(encontrado);

                }
                catch (DaoException ex) {
                    Logger.getLogger(ViewGrupo.class.getName()).log(Level.SEVERE, null, ex);
                }

                facade.editarUsuario(u);
                JOptionPane.showMessageDialog(null, "Usuário editado com sucesso!");
            }
            catch (DaoException ex) {
                Logger.getLogger(ViewPermissao.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Não foi possível editar esse Usuário!");
            }
            finally {
                bntAdicionar.setEnabled(true);
                limparCampos();
                povoarTabelaUsuario();
            }

        }
    }//GEN-LAST:event_bntEditarActionPerformed

    private void bntExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntExcluirActionPerformed
        if (txtCpf.getText().toString().equals(null) && txtNome.getText().toString().equals(null) && txtGrupo.getText().toString().equals(null) && txtId.getText().toString().equals(null)
                || txtCpf.getText().toString().equals("") && txtNome.getText().toString().equals("") && txtGrupo.getText().toString().equals(null) && txtId.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Erro ao Excluir Usuário, Dados inválidos!");
        } else {
            Usuario u = SimpleFactoryUtil.criarUsuario();
            try {
                u = facade.buscarUsuario(Long.parseLong(txtId.getText().toString()));
                facade.removerUsuario(u, u.getId());
                JOptionPane.showMessageDialog(null, "Usuário Removido com sucesso!");
                povoarTabelaUsuario();

            }
            catch (DaoException ex) {
                Logger.getLogger(ViewPermissao.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Não foi possível Excluir esse usuário!");
            }
            finally {
                bntAdicionar.setEnabled(true);
                limparCampos();
                povoarTabelaUsuario();
            }

        }
    }//GEN-LAST:event_bntExcluirActionPerformed

    private void tblGrupoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblGrupoAncestorAdded
        DefaultTableModel table = (DefaultTableModel) tblGrupo.getModel();

        Facade facade = new Facade();
        List<Grupo> lista;
        try {
            lista = facade.listarGrupo();
            while (table.getRowCount() > 0) {
                table.removeRow(0);
            }

            for (Grupo g : lista) {
                table.addRow(new Object[]{
                    g.getId(),
                    g.getNome(),
                    g.getPermissoes()
                });
            }
        }
        catch (DaoException ex) {
            Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblGrupoAncestorAdded

    private void bntAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAdicionarActionPerformed
        if (txtCpf.getText().toString().equals(null) && txtNome.getText().toString().equals(null) && txtGrupo.getText().toString().equals(null) && txtId.getText().toString().equals(null)
                || txtCpf.getText().toString().equals("") && txtNome.getText().toString().equals("") && txtGrupo.getText().toString().equals("") && txtId.getText().toString().equals("") && txtSenha.getText().toString().equals("")) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar Usuário, Dados inválidos!");
        } else {
            Usuario u = SimpleFactoryUtil.criarUsuario();
            Grupo encontrado = SimpleFactoryUtil.criarGrupo();
            try {
                encontrado = facade.buscarGrupo(Long.parseLong(txtGrupo.getText()));
                u.setGrupo(encontrado);

            }
            catch (DaoException ex) {
                Logger.getLogger(ViewGrupo.class.getName()).log(Level.SEVERE, null, ex);
            }

            u.setNome(txtNome.getText());
            u.setCpf(Long.parseLong(txtCpf.getText()));
            u.setSenha(txtSenha.getText());
            
            try {
                facade.salvarUsuario(u);
                JOptionPane.showMessageDialog(null, "Usuário Cadastrado com Sucesso!");

            }
            catch (Exception e) {
                Logger.getLogger(ViewGrupo.class.getName()).log(Level.SEVERE, null, e);
                JOptionPane.showMessageDialog(null, "Erro ao cadastrar Usuário!");

            }
            finally {
                limparCampos();
                povoarTabelaUsuario();

            }

        }


    }//GEN-LAST:event_bntAdicionarActionPerformed

    private void tblUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuarioMouseClicked
        setarCampos();
    }//GEN-LAST:event_tblUsuarioMouseClicked

    private void txtGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGrupoMouseClicked
        txtGrupo.setText("");
        JOptionPane.showMessageDialog(null, "Informe nesse campo o código do grupo que deseja vincular a este usuário conforme o exemplo demonstrou ");       // TODO add your handling code here:
    }//GEN-LAST:event_txtGrupoMouseClicked

    private void txtGrupoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtGrupoMousePressed
        txtGrupo.setText("");
        JOptionPane.showMessageDialog(null, "Informe nesse campo o código do grupo que deseja vincular a este usuário conforme o exemplo demonstrou ");       // TODO add your handling code here:
    }//GEN-LAST:event_txtGrupoMousePressed
    private void limparCampos() {
        txtCpf.setText("");
        txtNome.setText("");
        txtGrupo.setText("");
        txtId.setText("");
        txtSenha.setText("");
    }

    private void povoarTabelaUsuario() {
        DefaultTableModel table = (DefaultTableModel) tblUsuario.getModel();

        Facade facade = new Facade();
        List<Usuario> lista;
        try {
            lista = facade.listarUsuario();
            while (table.getRowCount() > 0) {
                table.removeRow(0);
            }

            for (Usuario u : lista) {
                table.addRow(new Object[]{
                    u.getId(),
                    u.getCpf(),
                    u.getNome(),
                    u.getGrupo()
                });
            }
        }
        catch (DaoException ex) {
            Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setarCampos() {
        int setar = tblUsuario.getSelectedRow();//
        
   //     txtSenha.setText(tblUsuario.getModel().getValueAt(setar, 4).toString());
        txtGrupo.setText(tblUsuario.getModel().getValueAt(setar, 3).toString());
        txtNome.setText(tblUsuario.getModel().getValueAt(setar, 2).toString());
        txtCpf.setText(tblUsuario.getModel().getValueAt(setar, 1).toString());
        txtId.setText(tblUsuario.getModel().getValueAt(setar, 0).toString());
        bntAdicionar.setEnabled(false);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAdicionar;
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton bntExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGrupo;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
